# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import dashboard_pb2 as dashboard__pb2


class DashboardStub(object):
    """package dashboard;

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDashboard = channel.unary_unary(
                '/Dashboard/GetDashboard',
                request_serializer=dashboard__pb2.DashboardRequest.SerializeToString,
                response_deserializer=dashboard__pb2.DashboardResponse.FromString,
                )


class DashboardServicer(object):
    """package dashboard;

    """

    def GetDashboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DashboardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDashboard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDashboard,
                    request_deserializer=dashboard__pb2.DashboardRequest.FromString,
                    response_serializer=dashboard__pb2.DashboardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Dashboard', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Dashboard(object):
    """package dashboard;

    """

    @staticmethod
    def GetDashboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Dashboard/GetDashboard',
            dashboard__pb2.DashboardRequest.SerializeToString,
            dashboard__pb2.DashboardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
