# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dashboard.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dashboard.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x64\x61shboard.proto\"6\n\x05Panel\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x61ta_source\x18\x03 \x01(\t\"\x1e\n\x10\x44\x61shboardRequest\x12\n\n\x02id\x18\x01 \x01(\t\"E\n\x11\x44\x61shboardResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x06panels\x18\x04 \x03(\x0b\x32\x06.Panel2B\n\tDashboard\x12\x35\n\x0cGetDashboard\x12\x11.DashboardRequest\x1a\x12.DashboardResponseb\x06proto3'
)




_PANEL = _descriptor.Descriptor(
  name='Panel',
  full_name='Panel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Panel.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='Panel.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_source', full_name='Panel.data_source', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=73,
)


_DASHBOARDREQUEST = _descriptor.Descriptor(
  name='DashboardRequest',
  full_name='DashboardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DashboardRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=105,
)


_DASHBOARDRESPONSE = _descriptor.Descriptor(
  name='DashboardResponse',
  full_name='DashboardResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DashboardResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='DashboardResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='panels', full_name='DashboardResponse.panels', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=176,
)

_DASHBOARDRESPONSE.fields_by_name['panels'].message_type = _PANEL
DESCRIPTOR.message_types_by_name['Panel'] = _PANEL
DESCRIPTOR.message_types_by_name['DashboardRequest'] = _DASHBOARDREQUEST
DESCRIPTOR.message_types_by_name['DashboardResponse'] = _DASHBOARDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Panel = _reflection.GeneratedProtocolMessageType('Panel', (_message.Message,), {
  'DESCRIPTOR' : _PANEL,
  '__module__' : 'dashboard_pb2'
  # @@protoc_insertion_point(class_scope:Panel)
  })
_sym_db.RegisterMessage(Panel)

DashboardRequest = _reflection.GeneratedProtocolMessageType('DashboardRequest', (_message.Message,), {
  'DESCRIPTOR' : _DASHBOARDREQUEST,
  '__module__' : 'dashboard_pb2'
  # @@protoc_insertion_point(class_scope:DashboardRequest)
  })
_sym_db.RegisterMessage(DashboardRequest)

DashboardResponse = _reflection.GeneratedProtocolMessageType('DashboardResponse', (_message.Message,), {
  'DESCRIPTOR' : _DASHBOARDRESPONSE,
  '__module__' : 'dashboard_pb2'
  # @@protoc_insertion_point(class_scope:DashboardResponse)
  })
_sym_db.RegisterMessage(DashboardResponse)



_DASHBOARD = _descriptor.ServiceDescriptor(
  name='Dashboard',
  full_name='Dashboard',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=178,
  serialized_end=244,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDashboard',
    full_name='Dashboard.GetDashboard',
    index=0,
    containing_service=None,
    input_type=_DASHBOARDREQUEST,
    output_type=_DASHBOARDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DASHBOARD)

DESCRIPTOR.services_by_name['Dashboard'] = _DASHBOARD

# @@protoc_insertion_point(module_scope)
